%YAML:1.0
names:
   - shelf_system_0
   - shelf_system_1
   - shelf_system_2
   - shelf_system_3
shelf_system_0:
   type: ShelfSystem
   width: 0.35
   height: 2.0 
   depth: 1.0 
   transform: !!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 1., 0., 0., 1.145, 0., 1., 0.,
          -0.525, 0., 0., 1., 1.0, 0.,
          0., 0., 1. ]
shelf_system_1:
   type: ShelfSystem
   width: 0.35
   height: 2.0 
   depth: 1.0 
   transform: !!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 1., 0., 0., 2.145, 0., 1., 0.,
          -0.525, 0., 0., 1., 1.0, 0.,
          0., 0., 1. ]
shelf_system_2:
   type: ShelfSystem
   width: 0.35
   height: 2.0 
   depth: 1.0 
   transform: !!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 1., 0., 0., 3.145, 0., 1., 0.,
          -0.525, 0., 0., 1., 1.0, 0.,
          0., 0., 1. ]
shelf_system_3:
   type: ShelfSystem
   width: 0.35
   height: 2.0 
   depth: 1.0 
   transform: !!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 1., 0., 0., 4.145, 0., 1., 0.,
          -0.525, 0., 0., 1., 1.0, 0.,
          0., 0., 1. ]
