%YAML:1.0
names:
   - shelf_system_1 
shelf_system_1:
   type: ShelfSystem
   width: 0.50
   height: 2.0 
   depth: 1.0 
   transform: !!opencv-matrix
      rows: 4
      cols: 4
      dt: d
      data: [ 1., 0., 0., -0.5, 0., 1., 0.,
          0.25, 0., 0., 1., 1.0, 0.,
          0., 0., 1. ]
